server:
  forward-headers-strategy: native
  port: 8080
  compression:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    spring.data.h2: INFO

spring:
  flyway:
    enabled: false
    #    locations: filesystem:db/migration,filesystem:db/testdata
    locations: db/migration
    table: migrations
    default-schema: gra_db
#    baseline-on-migrate: true
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: ${PEDIDOSAPI_SECURITY_AUTH-SERVER-URL}

