server:
  port: 8080
  compression:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
#    org.springframework.security: INFO
#    org.springframework.security.oauth2: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql: DEBUG
#    org.springframework: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG
#    spring.data.h2: DEBUG

spring:
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://supriodonto.local:8080
  #          issuer-uri: ${PEDIDOSAPI_SECURITY_AUTH-SERVER-URL}


awardsapi:
  database:
    host: 192.168.177.2
    port: 3306
    dbname: supriodonto_dev
    username: root
    password: 123456

  jwt:
    keystore:
      jks-location: base64:MIIK1AIBAzCCCn4GCSqGSIb3DQEHAaCCCm8EggprMIIKZzCCBb4GCSqGSIb3DQEHAaCCBa8EggWrMIIFpzCCBaMGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFIhLZkQxPcing0NGu5zHuORO9mjuAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQHXkFeyYZmNd7PHOUmJLWuwSCBNAK0V6QvqZ/JD1JeyL3xFInRuAOdyi/OfqMB7T8p3eS0dfwgbNp8j1QJ0eve0YK5YfeoEVocp2VdG52avSmfO8KyzjCAgljvYnBy2xrnbQFozZ5PD36+bCWIUv6JJ5EWgHkzObc/rf0kkDaxiMrBN9gYu931BGAD26jMKk/k0JudNxdiSqFDPtIpxxf/disv+qMg0h9DyGODAqCrhDFjoFHrjOeL0ILnH8a3LdRhot6w/+2MVvIQGF1FWEvEx1Hx2x2oDAPKXd2HRYllTHCHo4rY+4NT4TuHwLXoq11HrHpm5Hcd5bzpYwV90lNjKzZRgggsKJ5FgMr31youWJjsr9zhyD4sSnFmRwEXxgpOEMNVCq3141wdcgo0VWmTq19S2S0T2AkzuwV9pG3StTcycSOVSXUOzYsZdqbMTCntHrpF6US/AU4aP7Oj/A4a9EzxP1Z43gp29xr+oGddeevTQp4WZCVe5R2hdMpFMt/OiwfHLrvDSAx7+1FFvqU+jixdHHMoSVh1hG+DDx6vXOdqtDY3dJf5iIhN3X99f9iiwRAUR/I/VTwOMP5r4buzYidJEPQFs2Euoljps1o/QePBFjYgPh2WyichHkXC79po+BB9hYcFnIm71i8+HSMAIdjBg5tch7R9ODS4rmTyPHG4G9MkK5bcfwg8Dxwg8hqIdcL5i0hlqxMnVeBNp9a1aCOsbQSn9wMf2hRNBrHbm+Rr5pcRJdhz1GyofW1omxwbgIIwuO1CorM/wgIL4iws9zEPLrzkljw4J6MnlOVvxsxNbAGtUVyP9n1yWJgvQ0L6WTrMrnr/quMbRIET4G+a9Pw8Nfm1og0vbfqp2yDRJWJz2cKvjLyWSoH6XB+Dg8OiGhOQdikrmx02+xPSeKV5Oj9+IKg6VD2cPZzpMvY2H1AwWIqsQ2xcKr4vR+cKTWKK75Ck4xxK4OK70tVWOGU8RFC991yeQorNMen5J7I64C2q88TFbwtkFkiOPhtIQHJXej7I20uKmk3Iu2GzpxhmHedVR7wfJqFWRKtl7xAGNgkosSuGFWwV/i3ab1PqJFQjqyT3iyYhc09EN2ZS5zHO8cgWJOdSu0CP/gdxq5dd9iVaMzaqUwPm2qclDYjoqDu2dojCodWQh2z6+Eq4Scf6HxN+rIQLz3A/jYxUlJC38K90r8nreiKyAd0HhrUZ9W4/GYpi5UZZsZyiqSbTUSIIedpXZpZGLzYqgBobZ8ZcWRs7MFK8adL/Z2GqQk4EQLIBs/5Rrws+S6vlXMRg/gLCFLoMZVGg+qk8Dt0xZhrpfxV4f5QtKjXRtDCytMi+nPOoTTQ5esX2aWsXA0c0xNmSGUbmoqs3a3VszhFNKnbDxQLrEIw3t2oRBzRYI3RNHURnoEb/lJ+xnKT3Fit231wwTr5KcXkfMD7EnxBUsaohbv2UDOPORJ0GWkt5qCQDof2beC6Yj22Qx7ccGgZecwCXUj2CKxTZ/EVDTuR9hXlncX5hM+uf2ugBXLGtgaEk79lyssGM7Hkp1EyIQ50ezGx/sdQu7PhGLV2IweTfMcjqAr9pBSKWXMBwVCwD+Tn12iI8ElZ3GZtDoRyZ6U3rt5n6TBNfyezG/q797ER4+hnMKUfbH81Gw25ZYf8YgA502rSUnS5QTFQMCsGCSqGSIb3DQEJFDEeHhwAcABlAGQAaQBkAG8AcwBhAHAAaQAtAGQAZQB2MCEGCSqGSIb3DQEJFTEUBBJUaW1lIDE2OTM0NDI1MDU2NjgwggShBgkqhkiG9w0BBwagggSSMIIEjgIBADCCBIcGCSqGSIb3DQEHATBmBgkqhkiG9w0BBQ0wWTA4BgkqhkiG9w0BBQwwKwQUahZnZvT2GtCNulNQbpBtMCcDvo4CAicQAgEgMAwGCCqGSIb3DQIJBQAwHQYJYIZIAWUDBAEqBBBLn78mMXPW5404mSLaUpFMgIIEEIxZMvohPyFifGJnr1ZxFvuc2Ry7zJzviod7FjsM1m68aU2Y8Z7T/6TMdddiUgdvOyyuIvrBD0PD/ww/hu5wMFA2NTqDJduFDDYvSq1lWobj0/K97onaR1H2o+dTvf5IcwpoRtmy857W6aQ4fLeiwdUVTA0QExzXYvqfct9rwRLRDxAUa+Gz+zQnqe/ZaiYRLbQ8FcY4s3Sc/N8xROyu0DZ1r9TXDSNBFbN/ksykLt82ALM8Z/oQSCf94S5Wf0RpUnuCsHcq69O8XdGhLZCZxfz7s2dD8QrRzeWCen6DWi14vJJARSPdbdCNwdUL3owlXaS+GedsSfsSe/u+Gr4UKH3XzW2+bavtm6lBMd5k5XVP/TR9V06nor9wjW175KI+iPCkM+W7CVwn9fiFJxZczT5aGtE4MYLKAA12yY6/okykK65QBk2pEXw7vLApKO0D3SlzOLdGUFWjophtGPgotlYmvYPJirr8VhKFjdz6FdhQjXz1iX0rg0HDEgpkHuBElV3RNSSzfS4xBomR0czySZmvjMIvB+AGGtUQpq/fJ/KqE4O5TFdMz0Si48t3QZexOCZby00z5aBqG7Edrw1CB3H7yVWRoPB5Y7Zj38rhbaMuCiV4KPN1baSsRqVyGk5Wdj3tS/sGmWcuDtexnl8GGyT6S/q6NCXiXS8EBOHhDu2P7aLL1vrJmgmsgPLvHtaeFRMNgX7WyD6I1zzt5PuLVjHtFkajBnOfY2ET69sHHlVabkt2xBEje6WhfRrp2jjBDDBRWgOZlQex5vOV3XT0MNC7V+QFw/BKdJlK+8JnaPm4y5ZwYiLW2XmC3PB9C++EKk1twlK7zAYVcIm4NLfug1uC8KY22Aq76usqH3+zyJ10ntXuirwseLXooJcAZEoBJJOBZpl2p9K1r+U4N9AJNZZPLPIUr7LhEW4seJFoGB9FVAZXSe19K9W/e+GPDEC7+/ZTOc2W/A7MasdQjpT5/Ais9SWn5E4Sf2vEKhtgrLM0bYSbq/XICI2Z/0bJ3C+NKscLmEzUFkEvG/jSEgY94UTf27ODfi0DpSBeW71DSc8k9Lru8ubjvjMDsFND57jOj4ESKRm6tjca7n815ltZ3c5UZZ55u+Gb6fO7VZ4ErgiG3LwgSrF1QcKXj///tGDOyXKiddoGLqVSvk8CUsHgvOBZhcoiUxI5g05/AX+0ocD2BS1GHtm5QnE4Vh/JSah9J4irl8v3DujwEyYJnM2xeE3kNEq6/xL1R64q9Wks3uNCVYdtVvYepm3uySuUNpYdMoNT79pnfMJjaoMMTk4dLpY95jUBBjqaERiS/cezZehGhNSs4vbFTmBuqgT5gwfZYyM/wJgMTefXhVhAnCf7g9pQLIk7tAEPr9vqIVDEdddmME0wMTANBglghkgBZQMEAgEFAAQgEZENbgQA2/S7hKgHgwwKx/hi+X9FBkMoV0hyiwXob30EFD6I7vGrL/RBEjygPNguuc4udSO1AgInEA==
      keypair-alias: pedidosapi-dev
      password: e1ffHourhjhnsfscvrdxaiax8rxaedbkDdmnqdfv
  security:
    admin-email-address: admin@supriodonto.com.br
    admin-init-password: $2a$12$BxTwwC/MknckK4locjeYFujlLOkRuWg33vZTYOEevsJ5B3Ox7ql2m
    allowed-redirects: http://supriodonto.local:8080/swagger-ui/oauth2-redirect.html,http://supriodonto.local:8080/login/oauth2/code/messaging-client-oidc,http://supriodonto.local:8080/authorized,https://oidcdebugger.com/debug,http://localhost:8080/swagger-ui/oauth2-redirect.html,http://localhost:8080/login/oauth2/code/messaging-client-oidc,http://localhost:8080/authorized,http://localhost:3000/oauth2-redirect.html,http://supriodonto.local:8090/callback
    auth-server-url: http://supriodonto.local:8080
    client-credentials:
      frontweb:
        client-id: frontweb
        client-password: $2a$12$BxTwwC/MknckK4locjeYFujlLOkRuWg33vZTYOEevsJ5B3Ox7ql2m
      integration:
        client-id: sest-api
        client-password: $2a$12$k0/KOMcvSakP3gBfWg8T/uY1SuDT/UKpYoF1qbQ9EZsn8o/070Emi
    origin-allowed: http://localhost:3000,https://d841-177-87-108-3.sa.ngrok.io
