spring:
  profiles:
    active: prod,ignore_cors
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  jpa:
    properties:
      hibernate:
#        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: "\"awards_schema\""
  datasource:
    url: jdbc:h2:mem:gra_db;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS "awards_schema";DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 60000
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    url: jdbc:h2:mem:gra_db
    locations: classpath:db/migration, classpath:db/data
    table: migrations
    default-schema: "awards_schema"
    user: sa
    password: password


springdoc:
  pathsToMatch: /**
  swagger-ui:
    path: /docs
    oauth:
      use-basic-authentication-with-access-code-grant: true
    show-extensions: true
    show-common-extensions: true

  model-converters:
    pageable-converter:
      enabled: true
  show-actuator: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  health:
    db:
      enabled: true

