spring:
  profiles:
    active: prod,ignore_cors
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:gra_db
    username: sa
    password: password
    hikari:
      maximum-pool-size: 1
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

springdoc:
  pathsToMatch: /**
  swagger-ui:
    path: /docs
#    oauth:
#      use-basic-authentication-with-access-code-grant: true
    show-extensions: true
    show-common-extensions: true

  model-converters:
    pageable-converter:
      enabled: true
  show-actuator: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  health:
    db:
      enabled: true

